# In order to build for production run:
# $ jekyll build --config _config.yml, _config-production.yml
#
#
# URL of static site
url: "https://production.devicetree.org"
# Destination folder
destination: production.devicetree.org
# Production boolean used in layouts / includes
production: true