title: DeviceTree
email: kyle.kirkby@linaro.org

description: > # this means to ignore newlines until "baseurl:"
    Devicetree.org is a community effort by many companies and individuals to facilitate the future evolution of the Devicetree Standard.
    The devicetree is a data structure for describing hardware. Rather than hard coding every detail of a device into an operating system,
    many aspects of the hardware can be described in a data structure that is passed to the operating system at boot time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.devicetree.org"

github_username:  devicetree

# Build settings
markdown: kramdown
theme: linaro-jekyll-theme

#Destination folder
destination: staging.devicetree.org

#Production Setting for Robots.txt
production: false

plugins:
  - jekyll-feed

include: [_content,]

jekyll_tidy: # Compress the html and beautify it.
    compress_html: true
    exclude: ["assets/**/*.js", robots.txt] #Add the js file to exclude to stop jekyll tidy errors.


paginate_path: /blog/:num/ # Pagination Path for Blogs

pagination:
    enabled: true
    per_page: 5
    trail:
        before: 2
        after: 2
    sort_reverse: true
    sort_field: 'date'

permalink: /blog/:title/ # Permalink for blog titles
